@echo off
REM ============================================================================
REM NIGHTWATCH Autonomous Observatory - Windows Installation Script (Step 622)
REM ============================================================================
REM
REM This script installs NIGHTWATCH on Windows systems.
REM Requirements: Python 3.10+, pip, Git (optional for updates)
REM
REM Usage: install.bat [options]
REM   --dev     Install development dependencies
REM   --skip-venv  Skip virtual environment creation
REM   --help    Show this help message
REM
REM ============================================================================

setlocal EnableDelayedExpansion

echo.
echo ============================================================
echo    NIGHTWATCH Autonomous Observatory - Windows Installer
echo ============================================================
echo.

REM Parse command line arguments
set DEV_MODE=0
set SKIP_VENV=0
set SHOW_HELP=0

:parse_args
if "%~1"=="" goto :done_args
if /i "%~1"=="--dev" set DEV_MODE=1
if /i "%~1"=="--skip-venv" set SKIP_VENV=1
if /i "%~1"=="--help" set SHOW_HELP=1
if /i "%~1"=="-h" set SHOW_HELP=1
shift
goto :parse_args
:done_args

if %SHOW_HELP%==1 (
    echo Usage: install.bat [options]
    echo.
    echo Options:
    echo   --dev        Install development dependencies
    echo   --skip-venv  Skip virtual environment creation
    echo   --help, -h   Show this help message
    echo.
    echo This script will:
    echo   1. Check Python version ^(requires 3.10+^)
    echo   2. Create a virtual environment ^(unless --skip-venv^)
    echo   3. Install required Python packages
    echo   4. Create necessary directories
    echo   5. Set up configuration files
    echo.
    exit /b 0
)

REM Check for Python
echo [1/6] Checking Python installation...
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found in PATH.
    echo Please install Python 3.10 or later from https://python.org
    exit /b 1
)

REM Check Python version
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
for /f "tokens=1,2 delims=." %%a in ("%PYTHON_VERSION%") do (
    set PYTHON_MAJOR=%%a
    set PYTHON_MINOR=%%b
)

echo Found Python %PYTHON_VERSION%

if %PYTHON_MAJOR% LSS 3 (
    echo ERROR: Python 3.10+ is required. Found version %PYTHON_VERSION%
    exit /b 1
)
if %PYTHON_MAJOR%==3 if %PYTHON_MINOR% LSS 10 (
    echo ERROR: Python 3.10+ is required. Found version %PYTHON_VERSION%
    exit /b 1
)
echo Python version OK.

REM Create virtual environment
if %SKIP_VENV%==0 (
    echo.
    echo [2/6] Creating virtual environment...
    if exist venv (
        echo Virtual environment already exists. Skipping creation.
    ) else (
        python -m venv venv
        if errorlevel 1 (
            echo ERROR: Failed to create virtual environment.
            exit /b 1
        )
        echo Virtual environment created.
    )

    REM Activate virtual environment
    echo Activating virtual environment...
    call venv\Scripts\activate.bat
    if errorlevel 1 (
        echo ERROR: Failed to activate virtual environment.
        exit /b 1
    )
) else (
    echo.
    echo [2/6] Skipping virtual environment creation ^(--skip-venv^)
)

REM Upgrade pip
echo.
echo [3/6] Upgrading pip...
python -m pip install --upgrade pip
if errorlevel 1 (
    echo WARNING: Failed to upgrade pip. Continuing anyway...
)

REM Install dependencies
echo.
echo [4/6] Installing Python dependencies...
if exist requirements.txt (
    pip install -r requirements.txt
    if errorlevel 1 (
        echo ERROR: Failed to install dependencies from requirements.txt
        exit /b 1
    )
) else (
    echo WARNING: requirements.txt not found. Installing core packages...
    pip install aiohttp pydantic numpy astropy pillow
)

REM Install development dependencies if requested
if %DEV_MODE%==1 (
    echo.
    echo Installing development dependencies...
    if exist requirements-dev.txt (
        pip install -r requirements-dev.txt
    ) else (
        pip install pytest pytest-asyncio pytest-cov black flake8 mypy
    )
)

REM Create necessary directories
echo.
echo [5/6] Creating directory structure...
if not exist data mkdir data
if not exist data\images mkdir data\images
if not exist data\logs mkdir data\logs
if not exist data\calibration mkdir data\calibration
if not exist data\catalogs mkdir data\catalogs
if not exist config mkdir config
if not exist tmp mkdir tmp
echo Directories created.

REM Create default configuration if needed
echo.
echo [6/6] Setting up configuration...
if not exist config\nightwatch.yaml (
    echo Creating default configuration file...
    (
        echo # NIGHTWATCH Configuration
        echo # Auto-generated by install.bat
        echo.
        echo observatory:
        echo   name: "My Observatory"
        echo   latitude: 0.0
        echo   longitude: 0.0
        echo   elevation_m: 0
        echo.
        echo camera:
        echo   simulator_mode: true
        echo   default_gain: 200
        echo   default_exposure_ms: 1000
        echo.
        echo safety:
        echo   enable_safety_monitor: true
        echo   wind_limit_mph: 25
        echo   humidity_limit_pct: 85
        echo.
        echo logging:
        echo   level: INFO
        echo   file: data/logs/nightwatch.log
    ) > config\nightwatch.yaml
    echo Default configuration created at config\nightwatch.yaml
) else (
    echo Configuration file already exists.
)

REM Installation complete
echo.
echo ============================================================
echo    Installation Complete!
echo ============================================================
echo.
echo Next steps:
echo   1. Edit config\nightwatch.yaml with your observatory settings
echo   2. Activate the virtual environment: venv\Scripts\activate.bat
echo   3. Run NIGHTWATCH: python -m nightwatch
echo.
if %DEV_MODE%==1 (
    echo Development mode installed. Run tests with: pytest
    echo.
)
echo For more information, see the documentation in docs\
echo.

endlocal
exit /b 0
